### PR TITLE
Adding a few tips for new members

### PR DESCRIPTION
**Pull request by mergesort**

### CODE REVIEW

**Comment by DanielTomlinson** [comment]
+1

**Comment by lazerwalker** [comment]
These are all really useful things to mention. Great idea!

I wonder if they should live somewhere else, though. It seems to me like there's a conceptual distinction between "here are things this community values and the sorts of behavior that are okay / not okay", and "here are very specific actions you should do that would be good etiquette". Both are valuable, but the latter doesn't really feel like a "code of conduct" to me. 

Can we set up a Slackbot auto-message to users when they first join?

**Comment by rodericj** [comment]
Seemd reasonable. I don't feel strongly one way or another but is it possible to turn that setting off?

**Comment by mergesort** [comment]
Slackbot auto message sounds like a smarter idea to me. I can rescind my PR, anyone got any other ideas of what to put into the auto message?

**Comment by rodericj** [comment]
So it would be: "@ channel hey everyone I'm awesome!", then slackbot would say: "Keep these to a minimum?"

If that is the case, I'd still recommend merging this in.

**Comment by lazerwalker** [comment]
I was imagining a DM from Slackbot when you join. Something along the lines
of "Welcome! Introduce yourself in #introductions, try to keep  @-channel
broadcasts to a minimum, and check out our [code of conduct]"

On Tue, Jan 20, 2015 at 12:45 PM, Roderic Campbell <notifications@github.com

**Comment by mergesort** [comment]
@rodericj I was thinking basically what @lazerwalker said, not an @channel message.

**Comment by mergesort** [comment]
According to @bradya there is no current way of doing this. Alternatively, how about a #welcome channel that has the ideas above. How does that sound?

There's also been a request before for this functionality it seems: https://twitter.com/liaodrake/status/532534819658686464

Reply: 
https://twitter.com/SlackHQ/status/533364938618961920

**Comment by lazerwalker** [comment]
Wonder if the Slack API has a hook for when a new user joins — we could wire our Hubot up to handle that.

**Comment by swizzlr** [comment]
The ReactiveX Slack locked posting in General, so nobody could inadvertently @everybody. I think @channel is sometimes justified for particular channels.

**Comment by mergesort** [comment]
Slack gives the option to turn off @everyone, @channel, or both. I like the idea of keeping @channel too, but don't see a way to disable it in #general only.

@lazerwalker There are API notifications in the real time messaging API for team_join and channel_join (which could be hooked into #general)
https://api.slack.com/events/team_join
https://api.slack.com/events/channel_joined

I'm 99% certain I won't have time or energy to setup Hubot to handle it though, so if anyone else is interested, I'd be glad to give you access to the repo/Heroku instance.

**Comment by AliSoftware** [comment]
I think adding an auto-message or DM from Slackbot when joining would be a great idea (especially to suggest to read this CoC, e.g. I didn't see it as the #general chan title at first, so I would have wanted that SlackBot suggests me to read it).

But I also feel we should still add this in the CoC (= merging this PR), as it falls under the "harassment is not ok" points, so imho this definitely has its place here.

**Comment by lazerwalker** [comment]
Yeah, looking back on this I'm totally fine with merging this in – no strong thoughts either way.

**Comment by mergesort** [comment]
Closed this out because we ended up building a bot that relays this information.

**Pull request closed without merging**
