### PR TITLE
Updated CoC with new admins

### PR DESCRIPTION
**Pull request by ohwhen**
This PR adds @BertaDevant, @christinamoulton and @danielpunkass as new admins and removes @jforbes, @nora and @earthabby following the update shared on Slack by Joe.

### CODE REVIEW

**Comment by christina** [comment]
hello, you have the wrong Christina FYI

**Comment by ohwhen** [comment]
@christina oops my apologies, these are Slack usernames but unfortunately GH linked them automatically to users here, please ignore.

**Comment by mergesort** [comment]
Thanks a lot @ohwhen, this is really helpful! (And turns out it's @cmoulton actually. 😄)

I do have a small request. It looks like a while back Slack changed their link format, and the links are no longer valid. Could I ask you to remove the links to admins altogether and bolding the text, since tapping on the link doesn't actually do anything in the current state?

**Comment by ohwhen** [comment]
Just pushed a new update, wasn't sure about the Slack usernames, so left them in. @mergesort let me know if this is fine?

**Comment by mergesort** [comment]
This is great, thanks!

**Pull request merged**
